### ISSUE TITLE
Another STM32F103C8T6

### ISSUE THREAD

**Issue by zoobab** [OliviliK/STM32F103#1]
I have also this one:

http://www.zoobab.com/arm-cortex-m3-stm32f103c8t6-stm32-core-board-development-boa

It is missing from your listing, maybe I can add some infos about it if you want.

**Comment by OliviliK** [comment]
Benjamin,
Thanks for your offer.  There are huge amount of boards that are missing from my lists.  I did try to have a wide representation of different STM32F103 boards and I included only those that I have been using myself.

I think that $10 is too much for this C8 board.  In my list, there is RB board (64 pin) from the same manufacturer for under $10.  The Smart v2.0 is a CB board (48 pin) and is available under $4.
